# Generated by Django 3.1.3 on 2021-04-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pre1',
            fields=[
                ('idpre1', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pre1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pre2',
            fields=[
                ('idpre2', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pre2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pre3',
            fields=[
                ('idpre3', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pre3',
                'managed': False,
            },
        ),
    ]
