# Generated by Django 3.1.3 on 2021-04-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Muslim',
        ),
        migrations.AlterField(
            model_name='djangorecomm',
            name='label',
            field=models.IntegerField(),
        ),
    ]
