# Generated by Django 3.1.3 on 2021-04-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pre3',
            options={'managed': True},
        ),
    ]
