# Generated by Django 3.1.3 on 2021-04-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20210402_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre4',
            fields=[
                ('idpre4', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pre4',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pre5',
            fields=[
                ('idpre5', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
